version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: varun-postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=varun
    ports:
      - "5432:5432"
    volumes:
      - varun-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: varun-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - varun-redis-data:/data

volumes:
  varun-db-data:
  varun-redis-data:
